import json
# Makine öğrenmesi ile ilgili anahtar kelimeler listesi
ml_keywords = [
    "makine öğrenmesi", "machine learning", "ml",
    "yapay zeka", "artificial intelligence", "ai",
    "veri", "data", "dataset", "veri seti", "veri kümesi",
    "veri analizi", "data analysis", "veri bilimi", "data science",
    "model", "modelleme", "model training", "model evaluation",
    "eğitim", "train", "training", "öğrenme", "learning",
    "test", "testing", "test seti", "validation", "doğrulama",
    "performans", "model performansı",
    "özellik", "feature", "feature engineering", "feature selection",
    "etiket", "label", "labeling", "etiketleme",
    "predict", "prediction", "tahmin",
    "sınıflandırma", "classification", "binary classification", "multi-class classification",
    "regresyon", "regression", "linear regression", "logistic regression", "lojistik regresyon", "doğrusal regresyon",
    "kümeleme", "clustering", "kümeler", "clusters",
    "k-en yakın komşu", "k-nn", "knn", "k nearest neighbor",
    "destek vektör makineleri", "svm", "support vector machine",
    "naive bayes", "bayes sınıflandırıcı", "bayesian",
    "karar ağacı", "decision tree", "random forest",
    "xgboost", "lightgbm", "gradient boosting", "gbm",
    "ağaç tabanlı model", "tree-based model",
    "derin öğrenme", "deep learning", "dl",
    "nöral ağ", "neural network", "nöral ağlar", "neural nets", "dnn",
    "cnn", "convolutional neural network",
    "rnn", "recurrent neural network", "gru", "lstm", "sequence model",
    "transformer", "transformer model", "attention",
    "gpt", "bert", "llm", "large language model", "roberta", "t5",
    "autoencoder", "vae", "generative model", "diffusion",
    "resnet", "mobilenet", "vgg", "inception", "efficientnet",
    "doğruluk", "accuracy", "precision", "recall", "f1", "f1 score",
    "auc", "roc", "confusion matrix", "karışıklık matrisi",
    "loss", "hata", "mse", "rmse", "mae", "log loss", "cross entropy",
    "denetimli", "supervised", "denetimsiz", "unsupervised",
    "takviyeli öğrenme", "reinforcement learning", "rl",
    "yarı denetimli", "semi-supervised", "self-supervised",
    "veri temizleme", "ön işleme", "preprocessing", "data cleaning",
    "boyut indirgeme", "dimensionality reduction", "pca", "tsne", "umap",
    "normalizasyon", "standardizasyon", "ölçekleme", "scaling", "standardization", "normalization",
    "grid search", "random search", "bayesian optimization",
    "cross validation", "cv", "k-fold",
    "hyperparameter tuning", "model optimization", "early stopping",
    "pipeline", "ml pipeline", "sklearn", "scikit-learn",
    "tensorflow", "keras", "pytorch", "torch", "jax",
    "huggingface", "transformers", "datasets library",
    "mlflow", "wandb", "tensorboard",
    "onnx", "model export", "savedmodel",
    "bias", "variance", "overfitting", "underfitting", "regularization",
    "dropout", "l1", "l2", "early stopping", "batch size", "learning rate",
    "generalization", "transfer learning", "fine-tuning",
    "embedding", "word embedding", "word2vec", "glove", "fasttext", "sentence embedding",
    "feature importance", "model yorumlanabilirliği", "explainability",
    "shap", "lime", "eli5", "interpretability",
    "id3", "c4.5", "cart",
    "boosting", "bagging", "stacking", "ensemble",
    "kaggle", "colab", "notebook", "jupyter"
]


# JSON dosyasına kaydetme
with open("ml_keywords.json", "w", encoding="utf-8") as f:
    json.dump(ml_keywords, f, ensure_ascii=False, indent=4)

print("Anahtar kelimeler 'ml_keywords.json' dosyasına kaydedildi.")
